###################################################################################################
# Recyclarr Configuration: WEB-1080p (V4)                                                         #
# Updated for Recyclarr v8.0+                                                                     #
# Documentation: https://recyclarr.dev                                                            #
# This config file is for use with Sonarr V4 only                                                 #
###################################################################################################

# Instance Definition: https://recyclarr.dev/reference/configuration/basic/
sonarr:
  web-1080p-v4:
    base_url: !secret sonarr_url
    api_key: !secret sonarr_api_key

    # Replaces 'sonarr-quality-definition-series' template
    quality_definition:
      type: series

    # Replaces 'sonarr-v4-quality-profile-web-1080p' template
    quality_profiles:
      - trash_id: dcf3a40bcecc55a6d55ef61502b48530 # WEB-1080p
        # If you wanted the alternative version, you would use this trash_id instead:
        # trash_id: 1111005a39cbfa2af98b03046bc1209b # WEB-1080p-alternative

# Custom Formats: https://recyclarr.dev/reference/configuration/custom-formats/
    custom_formats:
      # Optional
      - trash_ids:
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          # - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          # - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-1080p

      - trash_ids:
          # Uncomment the next six lines to allow x265 HD releases with HDR/DV
          # - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        # assign_scores_to:
          # - name: WEB-1080p
            # score: 0
      # - trash_ids:
          # - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
          - name: WEB-1080p
