---
- name: Create Sonarr group
  group:
    name: sonarr
    state: present

- name: Create Sonarr user
  user:
    name: sonarr
    groups: sonarr
    shell: /sbin/nologin
    append: true
    state: present
    create_home: false

- name: Install packages
  apt:
    pkg:
      - curl
      - mediainfo
      - sqlite3
    state: latest

- name: Create Sonarr directory if it does not exist
  file:
    path: /var/lib/sonarr
    state: directory
    mode: 0755

- name: Install Sonarr
  unarchive:
    src: https://services.sonarr.tv/v1/download/main/latest?version=4&os=linux
    dest: /opt/
    remote_src: true

- name: Synchronize Sonarr config from backup source
  synchronize:
    src: "/Sonarr-data/"
    dest: "/var/lib/sonarr/"
  delegate_to: "{{ inventory_hostname }}"

- name: Recursively change ownership of Sonarr directory
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: sonarr
    group: sonarr
  loop:
    - /opt/Sonarr
    - /var/lib/sonarr

- name: Copy systemd service file to server
  copy:
    src: sonarr.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start Sonarr

- name: Remove old cron job if it exists
  cron:
    name: "backup sonarr"
    state: absent

- name: Create backup cron job
  cron:
    name: "backup sonarr"
    weekday: "*"
    minute: "*/30"
    hour: "*"
    job: "rsync -qauz --no-perms --no-owner --no-group /var/lib/sonarr/ /Sonarr-data"
