---
- name: Create Sonarr group
  group:
    name: sonarr
    state: present

- name: Create Sonarr user
  user:
    name: sonarr
    groups: sonarr
    shell: /sbin/nologin
    append: true
    state: present
    create_home: false

- name: Install packages
  apt:
    pkg:
      - ca-certificates
      - gnupg
    state: latest

- name: Create Sonarr directory if it does not exist
  file:
    path: /var/lib/sonarr
    state: directory
    mode: 0755

- name: Synchronize Sonarr config from backup source
  synchronize:
    src: "/Sonarr-data/"
    dest: "/var/lib/sonarr/"
  delegate_to: "{{ inventory_hostname }}"

- name: Recursively change ownership of Sonarr directory
  file:
    path: /var/lib/sonarr
    state: directory
    recurse: true
    owner: sonarr
    group: sonarr

- name: Add Mono project apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

- name: Add the Mono repository
  apt_repository:
    repo: deb https://download.mono-project.com/repo/ubuntu stable-focal main
    filename: mono-official-stable
    state: present

- name: Add Sonarr project apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2009837CBFFD68F45BC180471F4F90DE2A9B4BF8

- name: Add the Sonarr repository
  apt_repository:
    repo: deb https://apt.sonarr.tv/ubuntu focal main
    filename: sonarr
    state: present

- name: Update repo cache
  changed_when: false
  apt:
    update_cache: true

- name: Install Sonarr
  apt:
    pkg:
      - sonarr
    state: latest

- name: Remove old cron job if it exists
  cron:
    name: "backup sonarr"
    state: absent

- name: Create backup cron job
  cron:
    name: "backup sonarr"
    weekday: "*"
    minute: "*/30"
    hour: "*"
    job: "rsync -qauz --no-perms --no-owner --no-group /var/lib/sonarr/ /Sonarr-data"
