---
- name: Create Prowlarr group
  group:
    name: prowlarr
    state: present

- name: Create Prowlarr user
  user:
    name: prowlarr
    groups: prowlarr
    shell: /sbin/nologin
    append: true
    state: present
    create_home: false

- name: Install packages
  apt:
    pkg:
      - curl
      - sqlite3
    state: latest

- name: Install Prowlarr
  unarchive:
    src: https://github.com/Prowlarr/Prowlarr/releases/download/v1.8.6.3946/Prowlarr.master.1.8.6.3946.linux-core-x64.tar.gz
    dest: /opt/
    remote_src: true
  notify:
    - Restart Prowlarr

- name: Recursively change ownership of Prowlarr directory
  file:
    path: /opt/Prowlarr
    state: directory
    recurse: true
    owner: prowlarr
    group: prowlarr

- name: Copy systemd service file to server
  copy:
    src: prowlarr.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start Prowlarr
