---
- name: Include my vars
  include_vars: /Users/matt/.ansible/.default_vars.yml

- name: Create Prowlarr group
  group:
    name: prowlarr
    gid: 10000
    state: present

- name: Create Prowlarr user
  user:
    name: prowlarr
    uid: 1000
    groups: prowlarr
    shell: /sbin/nologin
    append: true
    state: present
    create_home: false

- name: Install packages
  apt:
    pkg:
      - curl
      - sqlite3
    state: latest

- name: Install Prowlarr
  unarchive:
    src: https://github.com/Prowlarr/Prowlarr/releases/download/v2.3.5.5327/Prowlarr.master.2.3.5.5327.linux-core-x64.tar.gz
    dest: /opt/
    remote_src: true
  notify:
    - Restart Prowlarr
    
- name: Synchronize Prowlarr config from backup source
  synchronize:
    src: "/Prowlarr-data/"
    dest: "/var/lib/prowlarr"
  delegate_to: "{{ inventory_hostname }}"

- name: Recursively change ownership of Prowlarr directory
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: prowlarr
    group: prowlarr
  loop:
    - /opt/Prowlarr
    - /var/lib/prowlarr

- name: Copy systemd service file to server
  copy:
    src: prowlarr.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start Prowlarr

- name: Remove old cron job if it exists
  cron:
    name: "backup prowlarr"
    state: absent

- name: Create backup cron job
  cron:
    name: "backup prowlarr"
    weekday: "*"
    minute: "*/30"
    hour: "*"
    job: "rsync -qauzog /var/lib/prowlarr/ /Prowlarr-data"
