---
- name: Create Syncthing group
  group:
    name: syncthing
    gid: 10000
    state: present

- name: Create Syncthing user
  user:
    name: syncthing
    uid: 1000
    groups: syncthing
    shell: /bin/zsh
    append: true
    state: present
    create_home: true

- name: Copy .oh-my-zsh from root user
  copy:
    src: /root/.oh-my-zsh/
    dest: /home/syncthing/.oh-my-zsh/
    owner: syncthing
    group: syncthing
    mode: u=rwX,g=rX,o=rX
    remote_src: true

- name: Create .zshrc file
  copy:
    src: /root/.zshrc
    dest: /home/syncthing/.zshrc
    owner: syncthing
    group: syncthing
    mode: 0644
    remote_src: true

- name: Replace root with syncthing in .zshrc
  lineinfile:
    path: /home/syncthing/.zshrc
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: export DEFAULT_USER="root", line: export DEFAULT_USER="syncthing" }
    - { regexp: export ZSH=/root/.oh-my-zsh, line: export ZSH=/home/syncthing/.oh-my-zsh }

- name: Create Syncthing directories if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /var/lib/syncthing
    - /var/log/syncthing

- name: Create log file if it doesn't exist
  file:
    path: /var/log/syncthing/backup.log
    state: touch

- name: Get the config backups
  find:
    paths: "/mnt/app_config/syncthing/backups"
    patterns: 'syncthing-config-*.tar.gz'
  register: config_backups

- name: Get latest config backup
  set_fact:
    latest_config_backup: "{{ config_backups.files | sort(attribute='mtime',reverse=true) | first }}"
  when: config_backups.files | default('', true) | trim != ''

- name: Extract the latest config backup
  unarchive:
    src: "{{ latest_config_backup.path }}"
    dest: /var/lib/syncthing/
    remote_src: true
  when: latest_config_backup is defined
  notify:
    - Restart Syncthing

- name: Recursively change ownership of Syncthing directory
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: syncthing
    group: syncthing
  loop:
    - /var/lib/syncthing
    - /var/log/syncthing

- name: Add Syncthing repository
  deb822_repository:
    name: syncthing
    types: [deb]
    uris: https://apt.syncthing.net/
    signed_by: https://syncthing.net/release-key.gpg
    suites: [syncthing]
    components: [stable-v2]
    state: present
    enabled: true
    install_python_debian: true

- name: Create systemd service directory
  file:
    path: /etc/systemd/system/syncthing@syncthing.service.d
    state: directory
    mode: 0755
    
- name: Copy systemd service file to server
  template:
    src: syncthing@syncthing.service.d/override.conf.j2
    dest: /etc/systemd/system/syncthing@syncthing.service.d/override.conf
    owner: root
    group: root
    mode: 0744
  notify:
    - Restart Syncthing

- name: Install syncthing package
  apt:
    pkg:
      - syncthing
    state: latest
  notify:
    - Restart Syncthing

- name: Copy logrotate file to server
  copy:
    src: logrotate.d/syncthing
    dest: /etc/logrotate.d/syncthing

- name: Run logrotate
  shell: logrotate /etc/logrotate.conf

- name: Create backup cron job
  cron:
    name: "backup syncthing"
    minute: "0"
    hour: "2"
    job: 'tar -czf /mnt/app_config/syncthing/backups/syncthing-config-$(date +\%F).tar.gz -C /var/lib/syncthing config.xml https-cert.pem https-key.pem cert.pem key.pem && find /mnt/app_config/syncthing/backups -name "syncthing-config-*.tar.gz" -mtime +7 -delete >> /var/log/syncthing/backup.log 2>&1'

- name: Create logrotate cron job
  cron:
    name: "logrotate"
    minute: "*/10"
    job: "logrotate /etc/logrotate.conf"
