- name: Download Ubuntu 20.04 (Focal Fossa) LXC image
  ansible.builtin.command:
    argv:
      - pveam
      - download
      - local
      - ubuntu-20.04-standard_20.04-1_amd64.tar.gz

- name: Download Ubuntu 18.04 (Bionic Beaver) LXC image
  ansible.builtin.command:
    argv:
      - pveam
      - download
      - local
      - ubuntu-18.04-standard_18.04.1-1_amd64.tar.gz

- name: Change ownership and set correct file/directory permissions
  include_tasks: setup_files.yml
  loop:
    - /mnt/storage/media/tv
    - /mnt/storage/media/movies
    - /mnt/storage/downloads/usenet
    - /mnt/storage/downloads/torrents

- name: Recursively change ownership of scratch share directory
  ansible.builtin.file:
    path: /mnt/storage/shares/scratch
    state: directory
    recurse: yes
    owner: "100000"
    group: "100118"

- name: Recursively change ownership of brian share directory
  ansible.builtin.file:
    path: /mnt/storage/shares/brian
    state: directory
    recurse: yes
    owner: "101000"

- name: Recursively change ownership of charlene share directory
  ansible.builtin.file:
    path: /mnt/storage/shares/charlene
    state: directory
    recurse: yes
    owner: "101001"
