- name: Create Tdarr group
  group:
    name: tdarr
    state: present

- name: Create Tdarr user
  user:
    name: tdarr
    groups: tdarr
    shell: /sbin/nologin
    append: yes
    state: present
    create_home: no

- name: Install packages
  apt:
    pkg:
      - unzip
      - gnupg
      - software-properties-common
    state: latest

- name: Add HandBrake stable repository from PPA
  ansible.builtin.apt_repository:
    repo: ppa:stebbins/handbrake-releases

- name: Install video transcoding packages
  apt:
    pkg:
      - ffmpeg
      - handbrake-cli
    state: latest
    update_cache: yes

- name: Install Tdarr Updater
  unarchive:
    src: https://f000.backblazeb2.com/file/tdarrs/versions/2.00.08/linux_x64/Tdarr_Updater.zip
    dest: /opt/Tdarr
    remote_src: yes

- name: Download Tdarr Node and Server
  ansible.builtin.command:
    argv:
      - /opt/Tdarr/Tdarr_Updater
    creates: /opt/Tdarr/Tdarr_Server

- name: Recursively change ownership of Tdarr directory
  ansible.builtin.file:
    path: /opt/Tdarr/
    state: directory
    recurse: yes
    owner: tdarr
    group: tdarr

- name: Copy Tdarr Server systemd service file
  copy:
    src: Tdarr_Server.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start Tdarr Server

- name: Copy Tdarr Node systemd service file
  copy:
    src: Tdarr_Node.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start Tdarr Node
