---
- name: Create Tdarr group
  group:
    name: tdarr
    state: present

- name: Create Tdarr user
  user:
    name: tdarr
    groups: tdarr
    shell: /sbin/nologin
    append: true
    state: present
    create_home: false

- name: Create tdarr home directory
  file:
    path: /home/tdarr
    state: directory
    owner: tdarr
    group: tdarr

- name: Install packages
  apt:
    pkg:
      - unzip
      - gnupg
    state: latest

- name: Install video transcoding packages
  apt:
    pkg:
      - ffmpeg
      - handbrake-cli
    state: latest
    update_cache: true

- name: Install Tdarr Updater
  unarchive:
    src: https://f000.backblazeb2.com/file/tdarrs/versions/2.00.15/linux_x64/Tdarr_Updater.zip
    dest: /opt/Tdarr
    remote_src: true

- name: Download Tdarr Node and Server
  command:
    argv:
      - /opt/Tdarr/Tdarr_Updater
    creates: /opt/Tdarr/Tdarr_Server

- name: Recursively change ownership of Tdarr directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: tdarr
    group: tdarr
  loop:
    - /opt/Tdarr/
    - /var/cache/tdarr/

- name: Copy Tdarr Server systemd service file
  copy:
    src: Tdarr_Server.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start Tdarr Server

- name: Copy Tdarr Node systemd service file
  copy:
    src: Tdarr_Node.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start Tdarr Node
