---
- name: Include my vars
  include_vars: /Users/matt/.ansible/.default_vars.yml
  
- name: Create SABnzbd group
  group:
    name: sabnzbd
    gid: 10000
    state: present

- name: Create SABnzbd user
  user:
    name: sabnzbd
    uid: 1000
    groups: sabnzbd
    shell: /sbin/nologin
    append: true
    state: present
    create_home: false

- name: Install packages
  apt:
    pkg:
      - apt-transport-https
      - gnupg
    state: latest

- name: Create Sabnzbd directory if it does not exist
  file:
    path: /opt/sabnzbd
    state: directory
    mode: 0755

- name: Add the Universe and Multiverse repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe multiverse"
    - "deb http://archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-updates universe multiverse"
    - "deb http://security.ubuntu.com/ubuntu/ {{ ansible_distribution_release }}-security universe multiverse"

- name: Add the SABnzbd repository Apt signing key
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x98703123e0f52b2be16d586ef13930b14bb9f05f
    state: present
    keyring: /etc/apt/trusted.gpg.d/sabnzbd.gpg

- name: Add the SABnzbd repository
  apt_repository:
    repo: deb [arch=amd64] https://ppa.launchpadcontent.net/jcfp/nobetas/ubuntu {{ ansible_distribution_release }} main
    filename: sabnzbd
    state: present

- name: Update repo cache
  changed_when: false
  apt:
    update_cache: true

- name: Install SABnzbd package
  apt:
    pkg:
      - sabnzbdplus
    state: latest

- name: Synchronize Sabnzbd config from backup source
  synchronize:
    src: "/Sabnzbd-data/"
    dest: "/opt/sabnzbd/data"
  delegate_to: "{{ inventory_hostname }}"

- name: Recursively change ownership of Sazarr directory
  file:
    path: /opt/sabnzbd/
    state: directory
    recurse: true
    owner: sabnzbd
    group: sabnzbd

- name: Copy SABnzbd config file
  template:
    src: sabnzbdplus.j2
    dest: /etc/default/sabnzbdplus
    owner: root
    group: root
  notify:
    - Start SABnzbd

- name: Remove old cron job if it exists
  cron:
    name: "backup sabnzbd"
    state: absent

- name: Create backup cron job
  cron:
    name: "backup sabnzbd"
    weekday: "*"
    minute: "*/30"
    hour: "*"
    job: "rsync -qauzog /opt/sabnzbd/data/ /Sabnzbd-data"
