---
- name: Upgrade dependencies
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
  tags: always

- name: Install zsh and powerline fonts
  ansible.builtin.apt:
    pkg:
      - language-pack-en
      - fonts-powerline
      - zsh
      - git
    state: latest

- name: Clone oh-my-zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /root/.oh-my-zsh
    depth: 1

- name: Set correct permissions for oh-my-zsh files
  ansible.builtin.file:
    path: /root/.oh-my-zsh/
    owner: root
    group: root
    mode: u=rwX,g=rX,o=rX
    recurse: true

- name: Create .zshrc file
  ansible.builtin.template:
    src: zshrc.j2
    dest: /root/.zshrc
    owner: root
    group: root
    mode: 0644

- name: Set zsh as default shell
  ansible.builtin.user:
    name: root
    shell: /bin/zsh

- name: Set authorized keys for MacbookPro, iPhone and gaming PC
  ansible.posix.authorized_key:
    user: root
    key: "{{ item }}"
    state: present
  loop:
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOnhPKxWPeKknPPIXqbfiXJbSEyQ8cBEIsdZ9vquwPl9 matt@Matthews-MBP"
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP+7gkYWyHKkc3SnvFie/+y2BvV6T2sOhcnky59qC553 matt@iphone13"
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHmJct/UiTZmHQ357Cmh+sWBojHs0JydZsof9Br+8WJb matt@gaming-pc"
