# Export Terraform variable values to an Ansible var_file
resource "local_file" "tf_ansible_vars_new" {
  content = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    # LXC Ids
    tf_bazarr_lxcid: ${var.bazarr_lxcid}
    tf_cockpit_lxcid: ${var.cockpit_lxcid}
    tf_network_lxcid: ${var.network_lxcid}
    tf_plex_lxcid: ${var.plex_lxcid}
    tf_prowlarr_lxcid: ${var.prowlarr_lxcid}
    tf_radarr_lxcid: ${var.radarr_lxcid}
    tf_lidarr_lxcid: ${var.lidarr_lxcid}
    tf_sabnzbd_lxcid: ${var.sabnzbd_lxcid}
    tf_sonarr_lxcid: ${var.sonarr_lxcid}
    tf_traefik_lxcid: ${var.traefik_lxcid}
    tf_wireguard_lxcid: ${var.wireguard_lxcid}
    tf_tailscale_lxcid: ${var.tailscale_lxcid}
    tf_seerr_lxcid: ${var.seerr_lxcid}
    tf_syncthing_lxcid: ${var.syncthing_lxcid}
    tf_cookcli_lxcid: ${var.cookcli_lxcid}
    tf_donetick_lxcid: ${var.donetick_lxcid}
    tf_multi_scrobbler_lxcid: ${var.multi-scrobbler_lxcid}
    tf_vaultwarden_lxcid: ${var.vaultwarden_lxcid}
    tf_starbase80_lxcid: ${var.starbase80_lxcid}
    tf_immich_lxcid: ${var.immich_lxcid}
    tf_slskd_lxcid: ${var.slskd_lxcid}

    # IPs
    tf_bazarr_ip: ${trimsuffix(var.bazarr_ip, "/24")}
    tf_cockpit_ip: ${trimsuffix(var.cockpit_ip, "/24")}
    tf_network_ip: ${trimsuffix(var.network_ip, "/24")}
    tf_plex_ip: ${trimsuffix(var.plex_ip, "/24")}
    tf_prowlarr_ip: ${trimsuffix(var.prowlarr_ip, "/24")}
    tf_radarr_ip: ${trimsuffix(var.radarr_ip, "/24")}
    tf_lidarr_ip: ${trimsuffix(var.lidarr_ip, "/24")}
    tf_sabnzbd_ip: ${trimsuffix(var.sabnzbd_ip, "/24")}
    tf_sonarr_ip: ${trimsuffix(var.sonarr_ip, "/24")}
    tf_traefik_ip: ${trimsuffix(var.traefik_ip, "/24")}
    tf_wireguard_ip: ${trimsuffix(var.wireguard_ip, "/24")}
    tf_pi_hole_primary_ip: ${trimsuffix(var.pi-hole-primary_ip, "/24")}
    tf_pi_hole_secondary_ip: ${trimsuffix(var.pi-hole-secondary_ip, "/24")}
    tf_recyclarr_ip: ${trimsuffix(var.recyclarr_ip, "/24")}
    tf_tailscale_ip: ${trimsuffix(var.tailscale_ip, "/24")}
    tf_seerr_ip: ${trimsuffix(var.seerr_ip, "/24")}
    tf_syncthing_ip: ${trimsuffix(var.syncthing_ip, "/24")}
    tf_cookcli_ip: ${trimsuffix(var.cookcli_ip, "/24")}
    tf_donetick_ip: ${trimsuffix(var.donetick_ip, "/24")}
    tf_multi_scrobbler_ip: ${trimsuffix(var.multi-scrobbler_ip, "/24")}
    tf_vaultwarden_ip: ${trimsuffix(var.vaultwarden_ip, "/24")}
    tf_starbase80_ip: ${trimsuffix(var.starbase80_ip, "/24")}
    tf_immich_ip: ${trimsuffix(var.immich_ip, "/24")}
    tf_slskd_ip: ${trimsuffix(var.slskd_ip, "/24")}

    # Passwords
    tf_cockpit_password: ${data.vault_kv_secret_v2.cockpit-pwd.data["password"]}
    DOC
  filename = "./tf_ansible_vars.yml"
}
