---
- name: Create Homepage group
  group:
    name: homepage
    gid: 10000
    state: present

- name: Create Homepage user
  user:
    name: homepage
    uid: 1000
    groups: homepage
    shell: /sbin/nologin
    append: true
    state: present
    create_home: false

- name: Install packages
  apt:
    pkg:
      - curl
    state: latest

- name: Create Homepage directories if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /opt/homepage
    - /root/.nvm
    - /root/.cache/node

- name: Add Homepage directory as safe in git config
  shell: >
    git config --global --add safe.directory /opt/homepage

- name: Set nvm environment
  copy:
    src: nvm.env
    dest: nvm.env
    mode: 0644

- name: Install nvm
  shell: >
    set -o pipefail &&
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.40.4/install.sh | bash
  args:
    executable: /bin/bash
    creates: /root/.nvm/nvm.sh
    chdir: /root/.nvm
  environment:
    NVM_DIR: /root/.nvm
  changed_when: false

- name: Install nodejs
  shell: >
    source /root/nvm.env &&
    nvm install 22
  args:
    executable: /bin/bash
    chdir: /root/.nvm
  changed_when: false

- name: Install pnpm
  shell: >
    source /root/nvm.env &&
    corepack enable pnpm
  args:
    executable: /bin/bash
    chdir: /root/.nvm
  changed_when: false

- name: Download Homepage
  git:
    repo: https://github.com/benphelps/homepage.git
    dest: /opt/homepage
    depth: 1
    force: true

- name: Create config directory
  file:
    path: /opt/homepage/config
    state: directory
    mode: 0755

- name: Install Homepage 
  shell: >
    source /root/nvm.env &&
    pnpm install --frozen-lockfile --silent
  args:
    executable: /bin/bash
    chdir: /opt/homepage
  environment:
    COREPACK_ENABLE_DOWNLOAD_PROMPT: '0'
  changed_when: false

- name: Build Homepage 
  shell: >
    source /root/nvm.env &&
    pnpm build
  args:
    executable: /bin/bash
    chdir: /opt/homepage
  environment:
    GENERATE_SOURCEMAP: 'false'
  changed_when: false

- name: Clear build cache
  shell: >
    source /root/nvm.env &&
    corepack use pnpm@latest &&
    pnpm store prune
  args:
    executable: /bin/bash
    chdir: /opt/homepage
  changed_when: false

- name: Copy config files from persistant storage
  copy:
    src: /Homepage-data/
    dest: /opt/homepage/config
    mode: 0755
    remote_src: true
    force: true

- name: Recursively change ownership of Homepage directory
  file:
    path: /opt/homepage/
    state: directory
    recurse: true
    owner: homepage
    group: homepage

- name: Copy shell script to sync config files
  copy:
    src: sync-config.sh
    dest: /root/sync-config.sh
    mode: +x

# - name: Copy config sync systemd service file
#   copy:
#     src: sync-config.service
#     dest: /etc/systemd/system
#     owner: root
#     group: root
#   notify:
#     - Start Config Sync

# - name: Copy Homepage systemd service file
#   copy:
#     src: homepage.service
#     dest: /etc/systemd/system
#     owner: root
#     group: root
#   notify:
#     - Start Homepage
