- name: Download Pi-hole installer
  when: ansible_hostname == "pi-hole-primary"
  get_url:
    url: https://install.pi-hole.net
    dest: ~/install-pihole.sh
    mode: 0740

- name: Copy Pi-hole setup config
  when: ansible_hostname == "pi-hole-primary"
  copy:
    src: setupVars.conf
    dest: /etc/pihole/
  register: setup_conf_copied
    
- name: Install Pi-hole
  when: setup_conf_copied.changed
  ansible.builtin.command:
    argv:
      - ~/install-pihole.sh
      - --unattended

- name: Copy Pi-hole Local DNS Records config
  copy:
    src: custom.list
    dest: /etc/pihole/
  notify:
    - Restart Pi-hole
