---
- name: Install unbound
  apt:
    pkg:
      - unbound
    state: latest

- name: Ensure unbound and Pi-Hole directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /etc/pihole
    - /var/log/unbound

- name: Create unbound log file
  file:
    path: /var/log/unbound/unbound.log
    state: touch

- name: Copy unbound config
  copy:
    src: pi-hole.conf
    dest: /etc/unbound/unbound.conf.d/
  notify:
    - Restart Unbound

- name: Download Pi-hole installer
  get_url:
    url: https://install.pi-hole.net
    dest: ~/install-pihole.sh
    mode: 0740

- name: Copy Pi-hole setup config
  template:
    src: setupVars.conf.j2
    dest: /etc/pihole/setupVars.conf
  register: setup_conf_copied

- name: Copy Pi-hole Local DNS Records config
  copy:
    src: custom.list
    dest: /etc/pihole/
  notify:
    - Restart Pi-hole

- name: Install Pi-hole
  when: setup_conf_copied.changed
  ansible.builtin.command:
    argv:
      - ~/install-pihole.sh
      - --unattended
