- name: Create NZBGet group
  group:
    name: nzbget
    state: present

- name: Create NZBGet user
  user:
    name: nzbget
    groups: nzbget
    shell: /sbin/nologin
    append: yes
    state: present
    create_home: no

- name: Download NZBGet
  get_url:
    url: https://github.com/nzbget/nzbget/releases/download/v21.2-r2333/nzbget-21.2-testing-r2333-bin-linux.run
    dest: /nzbget-21.2-r2333-bin-linux.run
    mode: 0744
  register: new_nzb_dowloaded

- name: Install NZBGet if not already installed
  when: new_nzb_dowloaded.changed
  ansible.builtin.command:
    argv:
      - /nzbget-21.2-r2333-bin-linux.run
      - --destdir
      - /opt/nzbget
  notify:
    Restart NZBGet

- name: Recursively change ownership of NZBGet directory
  ansible.builtin.file:
    path: /opt/nzbget/
    state: directory
    recurse: yes
    owner: nzbget
    group: nzbget

- name: Copy systemd service file to server
  copy:
    src: nzbget.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start NZBGet
