- name: Create NZBGet group
  group:
    name: nzbget
    state: present

- name: Create NZBGet user
  user:
    name: nzbget
    groups: nzbget
    shell: /sbin/nologin
    append: yes
    state: present
    create_home: no

- name: Download NZBGet
  get_url:
    url: https://github.com/nzbget/nzbget/releases/download/v21.1/nzbget-21.1-bin-linux.run
    dest: /nzbget-bin-linux.run
    mode: 0744
   
- name: Install NZBGet if not already installed
  ansible.builtin.command:
    argv:
      - /nzbget-bin-linux.run
      - --destdir
      - /opt/nzbget
    creates: /opt/nzbget

- name: Recursively change ownership of NZBGet directory
  ansible.builtin.file:
    path: /opt/nzbget/
    state: directory
    recurse: yes
    owner: nzbget
    group: nzbget

- name: Copy systemd service file to server
  copy:
    src: nzbget.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start NZBGet
