- name: Install packages
  apt:
    pkg:
      - apt-transport-https
      - gnupg
    state: latest
  tags: jellyfin

- name: Add the Universe repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ groovy universe"
    - "deb http://archive.ubuntu.com/ubuntu/ groovy-updates universe"
    - "deb http://security.ubuntu.com/ubuntu/ groovy-security universe"
  tags: jellyfin

- name: Add the jellyfin repository Apt signing key
  ansible.builtin.apt_key:
    url: https://repo.jellyfin.org/ubuntu/jellyfin_team.gpg.key
    state: present
    keyring: /etc/apt/trusted.gpg.d/jellyfin.gpg
  tags: jellyfin

- name: Add the jellyfin repository
  apt_repository:
    repo: deb [arch=amd64] https://repo.jellyfin.org/ubuntu groovy main
    filename: jellyfin
    state: present
  tags: jellyfin

- name: Update repo cache
  changed_when: false
  apt:
    update_cache: yes
  tags: jellyfin

- name: Install jellyfin package
  apt:
    pkg:
      - jellyfin
    state: latest
  tags: jellyfin
