---
- name: Include my vars
  include_vars: /Users/matt/.ansible/.default_vars.yml

- name: Install Traefik
  unarchive:
    src: https://github.com/traefik/traefik/releases/download/v2.10.5/traefik_v2.10.5_linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: true
  notify:
    - Restart Traefik

- name: Create Traefik group
  group:
    name: traefik
    state: present

- name: Create Traefik user
  user:
    name: traefik
    group: traefik
    shell: /sbin/nologin
    state: present
    create_home: false

- name: Set port binding capability on Traefik
  community.general.capabilities:
    path: /usr/local/bin/traefik
    capability: cap_net_bind_service+ep
    state: present

- name: Remove old Traefik config
  file:
    state: absent
    path: /etc/traefik/

- name: Copy Traefik config
  copy:
    src: traefik
    dest: /etc
    mode: 0755
  notify:
    - Restart Traefik

- name: Create config files from templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}" 
    mode: 0644
  loop:
    - { src: jellyfin.yml.j2, dest: /etc/traefik/config/jellyfin.yml }
    - { src: navidrome.yml.j2, dest: /etc/traefik/config/navidrome.yml }
  notify:
    - Restart Traefik

- name: Create Traefik config file
  template:
    src: traefik.yml.j2
    dest: /etc/traefik/traefik.yml
    mode: 0644
  notify:
    - Restart Traefik

- name: Create Traefik plugins and logs directories if they do not exist
  file:
    path: "{{ item }}"
    state: directory
    owner: traefik
    group: traefik
    mode: 0755
  loop:
    - "/etc/traefik/plugins-storage"
    - "/var/log/traefik"

- name: Copy systemd service file to server
  template:
    src: traefik.service.j2
    dest: /etc/systemd/system/traefik.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Start Traefik

- name: Copy logrotate file to server
  copy:
    src: logrotate.d/traefik
    dest: /etc/logrotate.d/traefik

- name: Run logrotate
  shell: logrotate /etc/logrotate.conf

- name: Remove old cron jobs if they exist
  cron:
    name: "{{ item }}"
    state: absent
  loop:
    - "copy traefik logs"
    - "logrotate"

- name: Create logs cron job
  cron:
    name: "copy traefik logs"
    weekday: "*"
    minute: "*/5"
    hour: "*"
    job: "rsync -qauz --delete --no-perms --no-owner --no-group /var/log/traefik/ /traefik-config/logs"

- name: Create logrotate cron job
  cron:
    name: "logrotate"
    weekday: "*"
    minute: "*/10"
    hour: "*"
    job: "logrotate /etc/logrotate.conf"
