---
- name: Install Traefik
  unarchive:
    src: https://github.com/traefik/traefik/releases/download/v2.6.6/traefik_v2.6.6_linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: true
  notify:
    - Restart Traefik

- name: Create Traefik group
  group:
    name: traefik
    state: present

- name: Create Traefik user
  user:
    name: traefik
    group: traefik
    shell: /sbin/nologin
    state: present
    create_home: false

- name: Set port binding capability on Traefik
  community.general.capabilities:
    path: /usr/local/bin/traefik
    capability: cap_net_bind_service+ep
    state: present

- name: Copy Traefik config
  copy:
    src: traefik
    dest: /etc
  notify:
    - Restart Traefik

- name: Copy systemd service file to server
  copy:
    src: traefik.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start Traefik
