- name: Restart Pi-hole
  command:
    argv:
      - pihole
      - restartdns

- name: Restart Unbound
  systemd:
    name: unbound
    state: restarted
    daemon_reload: true

- name: Stop unbound-resolvconf
  systemd:
    name: unbound-resolvconf
    state: stopped
    enabled: false
  
- name: Reboot
  reboot:
