---
- name: Start Plex
  systemd:
    name: plexmediaserver
    state: started
    enabled: true

- name: Restart Plex
  systemd:
    name: plexmediaserver
    state: restarted
    daemon_reload: true
