---
http:
  routers:
    to-bazarr:
      rule: "Host(`subtitles.home.lan`)"
      service: bazarr

  services:
    bazarr:
      loadBalancer:
        servers:
          - url: http://192.168.1.33:6767
