---
http:
  routers:
    to-firefly:
      rule: "Host(`finance.home.lan`)"
      service: firefly

  services:
    firefly:
      loadBalancer:
        servers:
          - url: http://firefly.home.lan
