---
http:
  routers:
    to-jellyfin:
      rule: "Host(`media.test`)"
      service: jellyfin
    to-jellyfin-secure:
      rule: "Host(`media.dipalma.duckdns.org`)"
      service: jellyfin
      tls:
        certResolver: letsencrypt

  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: http://192.168.1.10:8096
