---
http:
  routers:
    to-prowlarr:
      rule: "Host(`search.home.lan`)"
      service: prowlarr

  services:
    prowlarr:
      loadBalancer:
        servers:
          - url: http://192.168.1.32:9696
