---
http:
  routers:
    to-prowlarr:
      rule: "Host(`search.test`)"
      service: prowlarr

  services:
    prowlarr:
      loadBalancer:
        servers:
          - url: http://192.168.1.29:9696
