---
http:
  routers:
    to-qbittorrent:
      rule: "Host(`torrents.home.lan`)"
      service: qbittorrent

  services:
    qbittorrent:
      loadBalancer:
        servers:
          - url: http://192.168.10.31:8080
