http:
  routers:
    to-qbittorrent:
      rule: "Host(`torrents.test`)"
      service: qbittorrent

  services:
    qbittorrent:
      loadBalancer:
        servers:
          - url: http://192.168.1.15:8080
