---
http:
  routers:
    to-radarr:
      rule: "Host(`movies.home.lan`)"
      service: radarr

  services:
    radarr:
      loadBalancer:
        servers:
          - url: http://192.168.1.35:7878
