---
http:
  routers:
    to-syncthing:
      rule: "Host(`sync.test`)"
      service: syncthing

  services:
    syncthing:
      loadBalancer:
        servers:
          - url: http://192.168.1.36:8384
