---
- import_playbook: ./playbooks/bazarr.yml
- import_playbook: ./playbooks/cockpit.yml
- import_playbook: ./playbooks/donetick.yml
- import_playbook: ./playbooks/immich.yml
- import_playbook: ./playbooks/lidarr.yml
- import_playbook: ./playbooks/multi-scrobbler.yml
- import_playbook: ./playbooks/network.yml
- import_playbook: ./playbooks/pi-hole.yml
- import_playbook: ./playbooks/plex.yml
- import_playbook: ./playbooks/prowlarr.yml
- import_playbook: ./playbooks/radarr.yml
- import_playbook: ./playbooks/recyclarr.yml
- import_playbook: ./playbooks/sabnzbd.yml
- import_playbook: ./playbooks/samba.yml
- import_playbook: ./playbooks/seerr.yml
- import_playbook: ./playbooks/sonarr.yml
- import_playbook: ./playbooks/starbase80.yml
- import_playbook: ./playbooks/syncthing.yml
- import_playbook: ./playbooks/tailscale.yml
- import_playbook: ./playbooks/traefik.yml
- import_playbook: ./playbooks/wireguard.yml
