---
- name: Create Bazarr group
  group:
    name: bazarr
    state: present

- name: Create Bazarr user
  user:
    name: bazarr
    groups: bazarr
    shell: /sbin/nologin
    append: true
    state: present
    create_home: false

- name: Install packages
  apt:
    pkg:
      - python3-dev
      - python3-pip
      - python3-distutils
      - unrar
      - unzip
    state: latest

- name: Create Bazarr directory if it does not exist
  file:
    path: /opt/bazarr/data
    state: directory
    mode: 0755

- name: Install Bazarr
  unarchive:
    src: https://github.com/morpheus65535/bazarr/releases/download/v1.4.0/bazarr.zip
    dest: /opt/bazarr
    remote_src: true

- name: Install specified python requirements
  pip:
    requirements: /opt/bazarr/requirements.txt

- name: Synchronize Bazarr config from backup source
  synchronize:
    src: "/Bazarr-data/"
    dest: "/opt/bazarr/data"
  delegate_to: "{{ inventory_hostname }}"

- name: Recursively change ownership of Bazarr directory
  file:
    path: /opt/bazarr/
    state: directory
    recurse: true
    owner: bazarr
    group: bazarr

- name: Copy Bazarr systemd service file
  copy:
    src: bazarr.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start Bazarr

- name: Remove old cron job if it exists
  cron:
    name: "backup bazarr"
    state: absent

- name: Create backup cron job
  cron:
    name: "backup bazarr"
    weekday: "*"
    minute: "*/30"
    hour: "*"
    job: "rsync -qauz --no-perms --no-owner --no-group /opt/bazarr/data/ /Bazarr-data"
