---
- name: Reboot to ensure terraform provisioner config is applied
  reboot:
  
- name: Install required packages
  apt:
    pkg:
      - samba
    state: latest

- name: Create directories if they don't exist
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /storage/media/tv-shows
    - /storage/media/movies
    - /storage/media/pictures
    - /storage/downloads/nzbs
    - /storage/downloads/torrents
    - /storage/shares/matt

- name: Copy smb.conf file
  copy:
    src: smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Samba

- name: Create matt user
  user:
    name: matt
    groups: sambashare
    shell: /sbin/nologin
    append: true
    state: present
    create_home: false
  register: matt_created

- name: Prompt for user matt's samba password
  when: matt_created.changed
  pause:
    prompt: "Please enter user matt's samba password"
    echo: false
  register: result

- set_fact:
    matt_password: "{{ result.user_input }}"
  when: matt_created.changed

- name: Configure matt user
  when: matt_created.changed
  shell: >
    (pdbedit --user=matt 2>&1 > /dev/null)
    || (echo '{{ matt_password }}'; echo '{{ matt_password }}')
    | smbpasswd -s -a matt
