---
- name: Create Tautulli group
  group:
    name: tautulli
    state: present

- name: Create Tautulli user
  user:
    name: tautulli
    groups: tautulli
    shell: /sbin/nologin
    append: true
    state: present
    create_home: false

- name: Install packages
  apt:
    pkg:
      - python3
      - python3-setuptools
    state: latest

- name: Create Tautulli directories if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /opt/tautulli
    - /etc/tautulli

- name: Add Tautulli directory as safe in git config
  shell:
    cmd: git config --global --add safe.directory /opt/tautulli

- name: Install Tautulli
  git:
    repo: https://github.com/Tautulli/Tautulli.git
    dest: /opt/tautulli
    depth: 1
    force: true
    version: master

- name: Synchronize Tautulli config from backup source
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  delegate_to: "{{ inventory_hostname }}"
  loop:
    - { src: /Tautulli-data/tautulli.db, dest: /opt/tautulli/tautulli.db }
    - { src: /Tautulli-data/config.ini, dest: /etc/tautulli/config.ini }

- name: Recursively change ownership of Tautulli directory
  file:
    path: /opt/tautulli/
    state: directory
    recurse: true
    owner: tautulli
    group: tautulli

- name: Copy Tautulli systemd service file
  copy:
    src: tautulli.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start Tautulli

- name: Remove old cron jobs if they exist
  cron:
    name: "{{ item }}"
    state: absent
  loop:
    - backup tautulli data
    - backup tautulli config

- name: Create backup data cron job
  cron:
    name: "backup tautulli data"
    weekday: "*"
    minute: "*/30"
    hour: "*"
    job: "rsync -qauz --no-perms --no-owner --no-group /opt/tautulli/tautulli.db /Tautulli-data/"

- name: Create backup config  cron job
  cron:
    name: "backup tautulli config"
    weekday: "*"
    minute: "*/30"
    hour: "*"
    job: "rsync -qauz --no-perms --no-owner --no-group /etc/tautulli/config.ini /Tautulli-data/"
