---
- name: Create media group
  group:
    name: media
    state: present

- name: Create Lidarr user
  user:
    name: lidarr
    groups: media
    shell: /sbin/nologin
    append: true
    state: present
    create_home: false

- name: Install required packages
  apt:
    pkg:
      - curl
      - mediainfo
      - sqlite3
      - libchromaprint-tools
    state: latest

- name: Install Lidarr
  unarchive:
    src: https://github.com/Lidarr/Lidarr/releases/download/v1.0.2.2592/Lidarr.master.1.0.2.2592.linux-core-x64.tar.gz
    dest: /opt/
    remote_src: true

- name: Recursively change ownership of Lidarr directory
  ansible.builtin.file:
    path: /opt/Lidarr
    state: directory
    recurse: true
    owner: lidarr
    group: media

- name: Copy systemd service file to server
  copy:
    src: lidarr.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start Lidarr
